---
apiVersion: v1
kind: Service
metadata:
  name: postgres-b-service
  labels:
    app: postgres-b-service
spec:
  selector:
    app: postgres-b
  ports:
  - name: postgres-b  
    port: 5433
    targetPort: 5433

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-b
spec:
  selector:
    matchLabels:
      app: postgres-b-service
  serviceName: postgres-b-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-b-service
    spec:
      containers:
      - name: postgres-b
        image: mob
        imagePullPolicy: Never
        ports:
        - containerPort: 5433