---
apiVersion: v1
kind: Service
metadata:
  name: postgres-a-service
  labels:
    app: postgres-a-service
spec:
  selector:
    app: postgres-a
  ports:
  - name: postgres-a
    port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-a
spec:
  selector:
    matchLabels:
      app: postgres-a-service
  serviceName: postgres-a-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-a-service
    spec:
      containers:
      - name: postgres-a
        image: mob
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        