apiVersion: v1
kind: ConfigMap
metadata:
  name: mob-config
data:
  key: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mob-deployment
  labels:
    app: mob
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mob
  template:
    metadata:
      labels:
        app: mob
    spec:
      containers:
      - name: mob
        image: nikolaik/python-nodejs:python3.8-nodejs15
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mob-service
  labels:
    app: mob
spec:
  selector:
    app: mob
  ports:
  - Protocol: TCP  
    port: 5432
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mob-ingress
  labels:
    name: mob-ingress
spec:
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mob-service
            port: 
              number: <Port>
