---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker-service
spec:
  selector:
    app: worker
  ports:
  - name: worker  
    port: 4000
    targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker
        imagePullPolicy: Never
        resources:
          limits:
            memory: 500Mi
            cpu: 1000m
        ports:
        - containerPort: 4000
