apiVersion: v1
kind: Secret
metadata:
  name: postgres-b-config
  labels:
    app: postgres-b
type: Opaque
data:
  POSTGRES_DB: <identifier>
  POSTGRES_USER: <user>
  POSTGRES_PASSWORD: <password>
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-b
  labels:
    app: postgres-b
spec:
  selector:
    app: postgres-b
  ports:
  - Protocol: TCP  
    port: 5433
    targetPort: 5433
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-b
spec:
  selector:
    matchLabels:
      app: postgres-b
  serviceName: postgres-b
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-b
    spec:
      containers:
      - name: postgres-b
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
          name: postgres-b-config
        volumeMounts:
        - name: postgres-b-data
          mountPath: /sys/data
      volumes:
      - name: postgres-b-data
        persistentVolumeClaim:
          claimName: dataVolume